### ISSUE TITLE
java.lang.RuntimeException: No toolkit found

### ISSUE THREAD

**Issue by azatsh** [patrickfav/density-converter#13]
I have jdk 11 installed and tried running both exe and jar version of latest release but nothing started.
When I run jar from cmd I could see an error: "java.lang.RuntimeException: No toolkit found"
Which I assume happens because I don't have JavaFX installed. 
Would be great to mention that JavaFX is required addionally to jdk (in readme ?). 
Or show a message about that (UI popup form).

**Comment by azatsh** [comment]
After trying to install JavaFx I gave up (still same error). 
Eventually I downloaded previous release (which works with jdk 1.8) and sucessfully ran.

**Comment by patrickfav** [comment]
Since Java 11, JavaFX is not packaged with the SDK anymore. Quick solution is to use an SDK that has it pre-packaged like:

* [Azul](https://www.azul.com/downloads/?package=jdk-fx#zulu)
* [Liberica](https://bell-sw.com/pages/downloads/)

See also: [JavaFX packaged](https://stackoverflow.com/questions/58354622/javafx-is-missing-in-java-openjdk)
